version: '3.8'

services:
  db:
    image: mariadb:11.1.2
    container_name: ecommerce-container
    env_file:
      - ./.env
    environment:
      - MARIADB_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MARIADB_DATABASE=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_CONTAINER_PORT

  nodeapp:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - $NODE_LOCAL_PORT:$NODE_CONTAINER_PORT
